---

- name: Clone app repo
  git: repo={{git_repo_url}} dest={{git_repo_dir}} version={{git_repo_branch}}
  notify:
    - reload supervisor config
  tags: code

- name: Clear pip build dir
  file: path=/opt/venv/build state=absent
  tags: code

- name: Create a virtual env and install app requirements
  pip: requirements='requirements.txt' virtualenv=/opt/venv chdir={{git_repo_dir}}
  tags: code

- name: Copy the production settings file
  copy: src=local_settings.py dest={{django_project_dir}}/ips owner=root group=root

- name: Install gunicord
  pip: name=gunicorn virtualenv=/opt/venv chdir={{git_repo_dir}}

- name: Run collectstatic
  django_manage: >
      command=collectstatic
      app_path={{django_project_dir}}
      settings={{app_name}}.settings
      pythonpath={{django_project_dir}}
      virtualenv={{venv_dir}}
  tags: code

- name: Run syncdb
  django_manage: >
      command=syncdb
      app_path={{django_project_dir}}
      settings={{app_name}}.settings
      pythonpath={{django_project_dir}}
      virtualenv={{venv_dir}}
  tags: code

- name: Run DB migrations
  django_manage: >
      command=migrate
      app_path={{django_project_dir}}
      settings={{app_name}}.settings
      pythonpath={{django_project_dir}}
      virtualenv={{venv_dir}}
  tags: code
